### DISCUSSION TITLE
CI/CD Integration

### DISCUSSION THREAD

**Discussion by sprankhub** [elgentos/magento2-cypress-testing-suite#14] [General]
I am pretty sure you at Elgentos run the testing suite via GitLab, @peterjaap? Mind sharing the configuration for it? I will most probably look into running the testing suite via Bitbucket Pipelines. I'll happily share the configuration if anyone is interested.

**Comment by peterjaap** [comment]
Yes we do, but it's pretty simple;

```yaml
stages:
  - e2e

cypress:
  allow_failure: false
  dependencies: []
  before_script: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: e2e
  script:
    # install dependencies
    - if [ -f "package-lock.json" ]; then npm ci; fi
    # run Cypress tests, with dashboard key if it is set in the env vars
    - if [ ! -z $CYPRESS_DASHBOARD_KEY ] && [ -f "cypress.json" ]; then ELECTRON_EXTRA_LAUNCH_ARGS="--js-flags=--expose-gc --disable-dev-shm-usage" CYPRESS_EXCLUDE_TAGS=local npx cypress run --browser electron --record --key $CYPRESS_DASHBOARD_KEY --parallel; fi
    - if [ -z $CYPRESS_DASHBOARD_KEY ] && [ -f "cypress.json" ]; then ELECTRON_EXTRA_LAUNCH_ARGS="--js-flags=--expose-gc --disable-dev-shm-usage" CYPRESS_EXCLUDE_TAGS=local npx cypress run --browser electron; fi
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots

```

**Comment by norgeindian** [comment]
As we use Bitbucket Pipelines, maybe it's interesting for others, how it can be defined there:

```
          - step:
              name: Cypress tests
              size: 2x
              caches:
                - composer
                - node
              services:
                - mariadb
                - elasticsearch
                - cypress
                - mailhog
              script:
                - apt-get update && apt-get install -y libxslt1-dev libxml2-dev libicu-dev libpng-dev unzip openssh-client libfreetype6-dev libjpeg-dev default-mysql-client chromium chromium-driver libzip-dev libmagickwand-dev libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
                - mkdir -p /usr/share/man/man1 && apt-get install -y default-jre
                - docker-php-ext-configure gd --with-freetype --with-jpeg
                - docker-php-ext-install -j$(nproc) bcmath gd intl pdo_mysql soap sockets xsl zip
                # avoid memory issues - see https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html#check-php-settings
                - echo 'memory_limit = 3G' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini
                - find var generated pub/static pub/media app/etc -type d -exec chmod g+s {} +
                - chown -R :www-data .
                - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                - composer self-update
                - composer install
                - mysql -h 127.0.0.1 -u root -ppassword -e 'CREATE DATABASE `cypress-tests-db`;'
                - scp web-user@111.2.333.444:/var/www/share/bitbucket-pipelines/db.sql.gz .
                - gunzip db.sql.gz
                - mysql -h 127.0.0.1 -u root -ppassword cypress-tests-db < db.sql
                # https://github.com/netz98/n98-magerun2#fix-empty-authorization-tables
                - mysql -h 127.0.0.1 -u root -ppassword cypress-tests-db -e "INSERT INTO authorization_role (role_id, parent_id, tree_level, sort_order, role_type, user_id, user_type, role_name) VALUES (1, 0, 1, 1, 'G', 0, '2', 'Administrators')"
                - mysql -h 127.0.0.1 -u root -ppassword cypress-tests-db -e "INSERT INTO authorization_rule (rule_id, role_id, resource_id, privileges, permission) VALUES (1, 1, 'Magento_Backend::all', null, 'allow')"
                - bin/magento setup:install --base-url=http://127.0.0.1/ --db-host=127.0.0.1 --backend-frontname=admin --db-name=cypress-tests-db --db-user=root --db-password=password --admin-email=info@customgento.com --admin-user=admin --admin-password=password123! --admin-firstname=CustomGento --admin-lastname=Support --currency=EUR --timezone=Europe/Berlin --no-interaction
                - bin/magento config:set web/unsecure/base_url 'http://127.0.0.1/'
                - bin/magento config:set web/secure/base_url 'http://127.0.0.1/'
                - curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
                - apt-get install -y nodejs
                - npm ci
                - npm run build
                - bin/magento setup:static-content:deploy -f
                - bin/magento indexer:set-mode realtime
                - sed -ri -e "s!/var/www/html!$BITBUCKET_CLONE_DIR!g" /etc/apache2/sites-available/*.conf
                - sed -ri -e "s!/var/www/!$BITBUCKET_CLONE_DIR!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
                - a2enmod rewrite
                - service apache2 restart
                - mkdir -p var/session
                - chmod 777 var/session
                - NODE_ENV=develop npx cypress run
              artifacts:
                - cypress/screenshots/**
                - cypress/videos/**
                - var/log/**
                - var/report/**
                - /var/log/**
definitions:
  services:
    mariadb:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: password
    elasticsearch:
      image: lionslair/elasticsearch-bitbucket-pipelines
    cypress:
      image: cypress/browsers:latest
    mailhog:
      image: mailhog/mailhog
      logging:
        driver: 'none'  # disable saving logs
      ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web ui
```
